version: '3.4'
services:
  #PHP Service
  vote-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:fpm
    container_name: vote-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    network_mode: host

  #Konjungate REST API
  vote-rpc-rest:
    build:
      context: .
      dockerfile: ./rpc-rest/Dockerfile
    container_name: vote-rpc-rest
    restart: unless-stopped
    tty: true
    ports:
      - "3333:3333"
    working_dir: /rpc-rest
    volumes:
      - ./rpc-rest:/rpc-rest
    network_mode: host

  #Nginx Service
  vote-webserver:
    image: nginx:1.17.8-alpine
    container_name: vote-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    network_mode: host


#Postgres Service
  vote-db:
    image: postgres:alpine
    container_name: vote-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432"
    env_file:
      - ./.env # configure postgres
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/postgresql/data/
    network_mode: host

#Docker Networks
#networks:
#  app-network:
#    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
